// /src/utils/excelExport.js
import ExcelJS from 'exceljs';

const COMPANY_NAME = 'Zakaria Housing Agency Limited';

export const exportToExcel = (config) => {
  const {
    reportType,
    data,
    filters,
    companyInfo,
    user,
    title = 'Report'
  } = config;

  // Create workbook
  const workbook = new ExcelJS.Workbook();
  workbook.creator = companyInfo.name || COMPANY_NAME;
  workbook.lastModifiedBy = `${user?.first_name} ${user?.last_name}`;
  workbook.created = new Date();
  workbook.modified = new Date();
  
  // Create worksheet
  const worksheet = workbook.addWorksheet(`${title}`);
  
  // Add company header
  const headerRow1 = worksheet.addRow([companyInfo.name || COMPANY_NAME]);
  headerRow1.font = { size: 16, bold: true };
  headerRow1.alignment = { horizontal: 'center' };
  worksheet.mergeCells(`A1:F1`);
  
  const headerRow2 = worksheet.addRow([title]);
  headerRow2.font = { size: 14, bold: true };
  headerRow2.alignment = { horizontal: 'center' };
  worksheet.mergeCells(`A2:F2`);
  
  // Add report info
  worksheet.addRow([]); // Empty row
  worksheet.addRow(['Generated by:', `${user?.first_name} ${user?.last_name} (${user?.role})`]);
  worksheet.addRow(['Generated on:', new Date().toLocaleString()]);
  worksheet.addRow(['Total Records:', data.length]);
  
  if (filters.startDate || filters.endDate) {
    worksheet.addRow(['Date Range:', `${filters.startDate || ''} to ${filters.endDate || ''}`]);
  }
  
  if (filters.search) {
    worksheet.addRow(['Search Term:', filters.search]);
  }
  
  worksheet.addRow([]); // Empty row
  
  // Add table headers based on report type
  const { headers, rows } = prepareExcelData(reportType, data);
  
  // Add table header
  const headerRow = worksheet.addRow(headers);
  headerRow.eachCell((cell) => {
    cell.font = { bold: true };
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF3B82F6' } // blue-500
    };
    cell.font = { color: { argb: 'FFFFFFFF' }, bold: true };
    cell.alignment = { horizontal: 'center' };
    cell.border = {
      top: { style: 'thin' },
      left: { style: 'thin' },
      bottom: { style: 'thin' },
      right: { style: 'thin' }
    };
  });
  
  // Add data rows
  rows.forEach(rowData => {
    const row = worksheet.addRow(rowData);
    
    // Format numeric columns
    row.eachCell((cell, colNumber) => {
      cell.border = {
        top: { style: 'thin' },
        left: { style: 'thin' },
        bottom: { style: 'thin' },
        right: { style: 'thin' }
      };
      
      // Format currency columns
      if (headers[colNumber - 1]?.includes('Amount') || headers[colNumber - 1]?.includes('amount')) {
        cell.numFmt = '"KSh" #,##0';
      }
      
      // Format date columns
      if (headers[colNumber - 1]?.includes('Date') || headers[colNumber - 1]?.includes('date')) {
        cell.numFmt = 'dd/mm/yyyy';
      }
    });
  });
  
  // Auto-fit columns
  worksheet.columns.forEach(column => {
    let maxLength = 0;
    column.eachCell({ includeEmpty: true }, cell => {
      const columnLength = cell.value ? cell.value.toString().length : 10;
      if (columnLength > maxLength) {
        maxLength = columnLength;
      }
    });
    column.width = Math.min(maxLength + 2, 30);
  });
  
  // Add summary row if there's financial data
  if (reportType === 'payments' || reportType === 'revenue') {
    const totalAmount = data.reduce((sum, item) => sum + (item.amount || 0), 0);
    worksheet.addRow([]);
    const summaryRow = worksheet.addRow(['TOTAL', '', '', `KSh ${totalAmount.toLocaleString()}`, '', '']);
    summaryRow.font = { bold: true };
    summaryRow.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFF0F9FF' }
    };
  }
  
  // Add footer
  worksheet.addRow([]);
  const footerRow = worksheet.addRow([`${companyInfo.name || COMPANY_NAME} - Confidential Report`]);
  footerRow.font = { italic: true, color: { argb: 'FF6B7280' } };
  footerRow.alignment = { horizontal: 'center' };
  worksheet.mergeCells(`A${footerRow.number}:F${footerRow.number}`);
  
  // Generate and download
  workbook.xlsx.writeBuffer().then(buffer => {
    const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${reportType}_report_${new Date().getTime()}.xlsx`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  });
};

const prepareExcelData = (reportType, data) => {
  // Similar to PDF data preparation
  let headers = ['ID', 'Name', 'Date', 'Amount', 'Status'];
  let rows = [];
  
  switch (reportType) {
    case 'tenants':
      headers = ['Tenant ID', 'First Name', 'Last Name', 'Phone', 'National ID', 'Unit Code', 'Property', 'Status'];
      rows = data.map(item => [
        item.id?.substring(0, 8),
        item.first_name || '',
        item.last_name || '',
        item.phone_number || '',
        item.national_id || '',
        item.unit_code || 'N/A',
        item.property_name || 'N/A',
        item.is_active ? 'Active' : 'Inactive'
      ]);
      break;
      
    case 'payments':
      headers = ['Payment ID', 'Tenant', 'Phone', 'Amount', 'Payment Month', 'M-Pesa Code', 'Status', 'Date'];
      rows = data.map(item => [
        item.id?.substring(0, 8),
        item.tenant_name || `${item.first_name} ${item.last_name}`,
        item.phone_number || '',
        item.amount || 0,
        item.payment_month || 'N/A',
        item.mpesa_receipt_number || 'N/A',
        item.status || 'Pending',
        new Date(item.created_at || Date.now())
      ]);
      break;
      
    // Add more report types as needed
    default:
      rows = data.map((item, index) => [
        index + 1,
        item.name || item.first_name || 'N/A',
        new Date(),
        item.amount || 0,
        'Active'
      ]);
  }
  
  return { headers, rows };
};