// src/utils/pdfExport.js
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// Company branding
const COMPANY_NAME = 'Zakaria Housing Agency Limited';
const COMPANY_ADDRESS = 'Mombasa, Kenya';
const COMPANY_PHONE = '+254 XXX XXX XXX';

export const exportToPDF = (config) => {
  const {
    reportType,
    data,
    filters,
    companyInfo,
    user,
    title = 'Report'
  } = config;

  if (!data || data.length === 0) {
    alert('No data available to export. Please generate a report first.');
    return;
  }

  try {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFontSize(20);
    doc.setTextColor(40, 40, 40);
    doc.text(companyInfo?.name || COMPANY_NAME, pageWidth / 2, 20, { align: 'center' });

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(COMPANY_ADDRESS, pageWidth / 2, 28, { align: 'center' });
    doc.text(COMPANY_PHONE, pageWidth / 2, 34, { align: 'center' });

    // Title
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text(title, pageWidth / 2, 45, { align: 'center' });

    // Info
    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    let yPos = 55;

    const userName = user?.first_name && user?.last_name 
      ? `${user.first_name} ${user.last_name}`
      : 'Agent';
    const userRole = user?.role || 'agent';

    doc.text(`Generated by: ${userName} (${userRole})`, 14, yPos);
    yPos += 7;
    doc.text(`Generated on: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 14, yPos);
    yPos += 7;
    doc.text(`Total Records: ${data.length}`, 14, yPos);
    yPos += 7;

    if (filters?.startDate || filters?.endDate) {
      const dateRange = `${filters.startDate || 'Start'} to ${filters.endDate || 'End'}`;
      doc.text(`Date Range: ${dateRange}`, 14, yPos);
      yPos += 7;
    }

    if (filters?.search) {
      doc.text(`Search: ${filters.search}`, 14, yPos);
      yPos += 7;
    }

    doc.setDrawColor(200, 200, 200);
    doc.line(14, yPos + 2, pageWidth - 14, yPos + 2);
    yPos += 10;

    // Prepare table
    const { headers, rows } = prepareTableData(reportType, data);

    // Use autoTable as a function (v5.x method)
    autoTable(doc, {
      head: [headers],
      body: rows,
      startY: yPos,
      margin: { left: 14, right: 14 },
      headStyles: {
        fillColor: [59, 130, 246],
        textColor: [255, 255, 255],
        fontSize: 10,
        fontStyle: 'bold'
      },
      bodyStyles: { fontSize: 9 },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      theme: 'striped',
      didDrawPage: (data) => {
        // Add page numbers
        const pageCount = doc.internal.getNumberOfPages();
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(
          `Page ${data.pageNumber} of ${pageCount}`,
          pageWidth / 2,
          doc.internal.pageSize.getHeight() - 10,
          { align: 'center' }
        );
      }
    });

    // Footer on last page
    const finalY = doc.lastAutoTable?.finalY || yPos + 50;
    
    // Only add footer if there's space, otherwise it's handled by didDrawPage
    if (finalY < 270) {
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(
        `${companyInfo?.name || COMPANY_NAME} - Confidential Report`,
        pageWidth / 2,
        285,
        { align: 'center' }
      );
    }

    doc.save(`${reportType}_report_${Date.now()}.pdf`);
    
    console.log('✅ PDF exported successfully');
    return true;

  } catch (error) {
    console.error('PDF export failed:', error);
    alert(`Export failed: ${error.message}`);
    return false;
  }
};

const prepareTableData = (reportType, data) => {
  let headers = [];
  let rows = [];

  switch (reportType) {
    case 'tenants':
      headers = ['#', 'Tenant Name', 'Phone', 'Property', 'Unit', 'Rent (KSh)', 'Status'];
      rows = data.map((item, index) => [
        index + 1,
        `${item.first_name || ''} ${item.last_name || ''}`.trim() || item.name || 'N/A',
        item.phone_number || 'N/A',
        item.property_name || 'N/A',
        item.unit_code || 'N/A',
        (parseFloat(item.rent_amount || item.monthly_rent) || 0).toLocaleString(),
        item.is_active ? 'Active' : 'Inactive'
      ]);
      break;

    case 'payments':
      headers = ['#', 'Receipt No.', 'Tenant', 'Amount (KSh)', 'Month', 'Status', 'Date'];
      rows = data.map((item, index) => [
        index + 1,
        item.mpesa_receipt_number || item.id?.substring(0, 8) || 'N/A',
        item.tenant_name || `${item.first_name || ''} ${item.last_name || ''}`.trim() || 'N/A',
        (parseFloat(item.amount) || 0).toLocaleString(),
        item.payment_month || 'N/A',
        item.status || 'Pending',
        item.created_at ? new Date(item.created_at).toLocaleDateString() : 'N/A'
      ]);
      break;

    case 'properties':
      headers = ['#', 'Code', 'Property Name', 'Address', 'Total Units', 'Occupied', 'Available'];
      rows = data.map((item, index) => [
        index + 1,
        item.property_code || 'N/A',
        item.name || 'N/A',
        item.address || 'N/A',
        item.total_units || item.unit_count || 0,
        item.occupied_units || 0,
        item.available_units || item.available_units_count || 0
      ]);
      break;

    case 'complaints':
      headers = ['#', 'Title', 'Property', 'Priority', 'Status', 'Raised By', 'Date'];
      rows = data.map((item, index) => [
        index + 1,
        item.title || 'N/A',
        item.property_name || 'N/A',
        item.priority || 'Medium',
        item.status || 'Open',
        item.tenant_name || `${item.first_name || ''} ${item.last_name || ''}`.trim() || 'N/A',
        item.created_at ? new Date(item.created_at).toLocaleDateString() : 'N/A'
      ]);
      break;

    case 'water':
      headers = ['#', 'Tenant', 'Property', 'Unit', 'Amount (KSh)', 'Bill Month', 'Status'];
      rows = data.map((item, index) => [
        index + 1,
        item.tenant_name || `${item.first_name || ''} ${item.last_name || ''}`.trim() || 'N/A',
        item.property_name || 'N/A',
        item.unit_code || 'N/A',
        (parseFloat(item.amount) || 0).toLocaleString(),
        item.bill_month || 'N/A',
        item.status || 'Pending'
      ]);
      break;

    case 'sms':
      headers = ['#', 'Recipient', 'Message', 'Status', 'Attempts', 'Date'];
      rows = data.map((item, index) => [
        index + 1,
        item.recipient_phone || item.phone_number || 'N/A',
        (item.message || 'N/A').substring(0, 50) + (item.message?.length > 50 ? '...' : ''),
        item.status || 'Pending',
        item.attempts || 0,
        item.created_at ? new Date(item.created_at).toLocaleDateString() : 'N/A'
      ]);
      break;

    case 'revenue':
      headers = ['#', 'Month', 'Total Revenue (KSh)', 'Payments', 'Properties', 'Tenants', 'Avg Payment'];
      rows = data.map((item, index) => [
        index + 1,
        item.month || 'N/A',
        (parseFloat(item.total_revenue) || 0).toLocaleString(),
        item.payment_count || 0,
        item.property_count || 0,
        item.tenant_count || 0,
        (parseFloat(item.average_payment) || 0).toLocaleString()
      ]);
      break;

    default:
      headers = ['#', 'Name', 'Date', 'Amount (KSh)', 'Status'];
      rows = data.map((item, index) => [
        index + 1,
        item.name || item.first_name || item.tenant_name || 'N/A',
        item.created_at ? new Date(item.created_at).toLocaleDateString() : 'N/A',
        (parseFloat(item.amount) || 0).toLocaleString(),
        item.status || 'Active'
      ]);
  }

  // Ensure all rows have the correct number of columns
  rows = rows.map(row => {
    const paddedRow = [...row];
    while (paddedRow.length < headers.length) {
      paddedRow.push('N/A');
    }
    return paddedRow.slice(0, headers.length);
  });

  return { headers, rows };
};

// Debug helper - can be called from browser console
export const checkAutoTable = () => {
  try {
    const doc = new jsPDF();
    autoTable(doc, { head: [['Test']], body: [['Test']] });
    console.log('✅ autoTable is working correctly');
    return true;
  } catch (error) {
    console.error('❌ autoTable check failed:', error);
    return false;
  }
};