// src/utils/pdfExport.js
import jsPDF from 'jspdf';
import 'jspdf-autotable'; // ← Just import it. It extends jsPDF automatically.

// Company branding
const COMPANY_NAME = 'Zakaria Housing Agency Limited';
const COMPANY_ADDRESS = 'Mombasa, Kenya';
const COMPANY_PHONE = '+254 XXX XXX XXX';

export const exportToPDF = (config) => {
  const {
    reportType,
    data,
    filters,
    companyInfo,
    user,
    title = 'Report'
  } = config;

  if (!data || data.length === 0) {
    alert('No data available to export. Please generate a report first.');
    return;
  }

  try {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFontSize(20);
    doc.setTextColor(40, 40, 40);
    doc.text(companyInfo?.name || COMPANY_NAME, pageWidth / 2, 20, { align: 'center' });

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(COMPANY_ADDRESS, pageWidth / 2, 28, { align: 'center' });
    doc.text(COMPANY_PHONE, pageWidth / 2, 34, { align: 'center' });

    // Title
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text(title, pageWidth / 2, 45, { align: 'center' });

    // Info
    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    let yPos = 55;

    const userName = user?.first_name && user?.last_name 
      ? `${user.first_name} ${user.last_name}`
      : 'Agent';
    const userRole = user?.role || 'agent';

    doc.text(`Generated by: ${userName} (${userRole})`, 14, yPos);
    yPos += 7;
    doc.text(`Generated on: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 14, yPos);
    yPos += 7;
    doc.text(`Total Records: ${data.length}`, 14, yPos);
    yPos += 7;

    if (filters?.startDate || filters?.endDate) {
      const dateRange = `${filters.startDate || 'Start'} to ${filters.endDate || 'End'}`;
      doc.text(`Date Range: ${dateRange}`, 14, yPos);
      yPos += 7;
    }

    if (filters?.search) {
      doc.text(`Search: ${filters.search}`, 14, yPos);
      yPos += 7;
    }

    doc.setDrawColor(200, 200, 200);
    doc.line(14, yPos + 2, pageWidth - 14, yPos + 2);
    yPos += 10;

    // Prepare table
    const { headers, rows } = prepareTableData(reportType, data);

    // Use autoTable (it's guaranteed after import)
    doc.autoTable({
      head: [headers],
      body: rows,
      startY: yPos,
      margin: { left: 14, right: 14 },
      headStyles: {
        fillColor: [59, 130, 246],
        textColor: [255, 255, 255],
        fontSize: 10,
        fontStyle: 'bold'
      },
      bodyStyles: { fontSize: 9 },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      theme: 'striped'
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`${companyInfo?.name || COMPANY_NAME} - Confidential Report`, pageWidth / 2, 285, { align: 'center' });

    doc.save(`${reportType}_report_${Date.now()}.pdf`);

  } catch (error) {
    console.error('PDF export failed:', error);
    alert(`Export failed: ${error.message}`);
  }
};

const prepareTableData = (reportType, data) => {
  let headers = ['ID', 'Name', 'Date', 'Amount', 'Status'];
  let rows = [];

  switch (reportType) {
    case 'payments':
      headers = ['Payment ID', 'Tenant', 'Amount', 'Payment Month', 'Status', 'Date'];
      rows = data.map(item => [
        item.mpesa_receipt_number || item.id?.substring(0, 8) || 'N/A',
        item.tenant_name || `${item.first_name || ''} ${item.last_name || ''}`.trim() || 'N/A',
        `KSh ${(item.amount || 0).toLocaleString()}`,
        item.payment_month || 'N/A',
        item.status || 'Pending',
        item.created_at ? new Date(item.created_at).toLocaleDateString() : new Date().toLocaleDateString()
      ]);
      break;

    default:
      rows = data.map((item, index) => [
        index + 1,
        item.name || item.first_name || item.tenant_name || 'N/A',
        item.created_at ? new Date(item.created_at).toLocaleDateString() : 'N/A',
        `KSh ${(item.amount || 0).toLocaleString()}`,
        item.status || 'Active'
      ]);
  }

  rows = rows.map(row => {
    while (row.length < headers.length) row.push('N/A');
    return row.slice(0, headers.length);
  });

  return { headers, rows };
};

// Optional: Expose for debugging
export const checkAutoTable = () => !!jsPDF.API.autoTable;